appname: longform-nextjs
version: FROM_TAG
siteaddress: serwis-nextjs.onet.pl

# SDK Configuration
sdk_version: node_v14
handler: app.js#Server
automator_scripts: '@ras-tech/node-scripts'

# Opal Bus Configuration
npm:
  registry: https://registry.npmjs.org
servicename: commercial
interfaces:
  longform-nextjs:
    authentication: false
    authorisation: false
    ssl: false
hooks:
  postinstall: './postinstall.sh'
